[package]
name = "talmudifier"
version = "0.1.0"
edition = "2021"
authors = ["Esther Alter <subalterngames@gmail.com>"]
description = "Convert markdown text into Talmud-like PDFs"

[dependencies]
clap = "4.5.30"
talmudifier = { path = ".." }
